[profile.default]
src             = 'src'                                 # The source directory
out             = 'out'                                 # The output directory
libs            = ['lib']                               # A list of library directories
optimizer       = true                                  # Enable or disable the solc optimizer
optimizer_runs  = 200                                   # The number of optimizer runs
solc_version    = '0.8.26'                              # Override for the solc version
evm_version     = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
